apiVersion: v1
kind: Pod
metadata:
  name: assgnment
  labels:
    app: assgnment
spec:
  containers:
      - image: mehrjay86/mycv
        name:  html-generator
        volumeMounts:
          - name: html
            mountPath: /var/htdocs
      - image: nginx:alpine
        name: web-server
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ass-svc
spec:
  type: NodePort
  ports:
   - name: http 
     targetPort: 8080
     port: 80
   - name : https
     targetPort: 8443
     port: 443
  selector:
    app: assgnment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ass-pvc
  labels:
    app: assgnment
spec:
 storageClassName: manual
    accessModes:
     - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ass-pvv
  labels:
    type: local
    app : assgnment
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"